#!/usr/bin/env node
const PDFDocument = require('pdfkit'), fs = require('fs'), path = require('path');
const out = path.join(__dirname, 'public', 'downloads', 'guide-pl.pdf');
const logo = path.join(__dirname, 'public', 'grantunionLogo.png');
const doc = new PDFDocument({size: 'A4', margin: 15, bufferPages: true});
doc.pipe(fs.createWriteStream(out));
const arialPath = 'C:\\Windows\\Fonts\\arial.ttf';
const arialBoldPath = 'C:\\Windows\\Fonts\\arialbd.ttf';
doc.registerFont('Arial', arialPath);
doc.registerFont('ArialBold', arialBoldPath);
if (fs.existsSync(logo)) { const w = doc.page.width;doc.image(logo, (w - 75) / 2, 15, { width: 75, height: 50 });doc.moveDown(3);}
doc.fontSize(26).fillColor('#FF8C37').font('ArialBold').text('GRANT UNION', { align: 'center' });doc.moveDown(0.6);
doc.fontSize(18).fillColor('#FF8C37').font('ArialBold').text('Witamy w Grant Union');doc.moveTo(15, doc.y + 2).lineTo(580, doc.y + 2).strokeColor('#FF8C37').lineWidth(2.5).stroke();doc.moveDown(0.35);
doc.fontSize(10.5).fillColor('#444').font('ArialBold').text('Witamy w Grant Union, wiodącej na świecie platformie inwestycyjnej i handlowej. Zobowiązujemy się do zapewnienia Ci bezpiecznego, przejrzystego i zyskownego doświadczenia inwestycyjnego.', { width: 490, lineGap: 1.5 });doc.moveDown(0.25);
doc.fontSize(13).fillColor('#FF8C37').font('ArialBold').text('O Grant Union');doc.moveDown(0.2);
doc.fontSize(10.5).fillColor('#444').font('ArialBold').text('Grant Union to profesjonalna firma handlowa specjalizująca się w handlu kryptowalutami, handlu forex, złocie i inwestycjach nieruchomościowych. Nasz zespół profesjonalnych traderów pracuje z dedykacją, aby zmaksymalizować zwroty z Twoich inwestycji w Bitcoin.', { width: 490, lineGap: 1.5 });doc.moveDown(0.25);
doc.fontSize(12).fillColor('#FF8C37').font('ArialBold').text('Minimalna Inwestycja');doc.moveDown(0.15);
doc.fontSize(10.5).fillColor('#444').font('ArialBold').text('Firma oferuje prowizję dzienną na podstawie Twojego planu inwestycji. Z minimalnym depozytem zaledwie 100 $, możesz zacząć zarabiać. Po okresie inwestycji możesz wybrać wycofanie zarówno kapitału, jak i zysków, lub reinwestowanie na ciągły wzrost.', { width: 490, lineGap: 1.5 });
doc.addPage();
doc.fontSize(18).fillColor('#FF8C37').font('ArialBold').text('Plany Inwestycji i Zwroty');doc.moveTo(15, doc.y + 2).lineTo(580, doc.y + 2).strokeColor('#FF8C37').lineWidth(2.5).stroke();doc.moveDown(0.35);
const t = doc.y;
doc.fontSize(11).font('ArialBold').fillColor('#ffffff');
doc.rect(15, t, 565, 22).fillColor('#FF8C37').fill();
doc.fillColor('#ffffff');
doc.text('Plan', 20, t + 6, { width: 90 });
doc.text('Czas', 110, t + 6, { width: 110 });
doc.text('Prowizja Dzienna', 220, t + 6, { width: 100 });
doc.text('Min. Dep.', 330, t + 6, { width: 85 });
doc.text('Max. Dep.', 430, t + 6, { width: 85 });
const r = [['Plan 3 dni', '3 dni', '8%', '$100', '$999'], ['Plan 7 dni', '7 dni', '3%', '$599', '$3,999'], ['Plan 12 dni', '12 dni', '3.5%', '$1,000', '$4,999'], ['Plan 15 dni', '15 dni', '4%', '$3,000', '$9,000'], ['Plan 3 miesięcy', '90 dni', '4%', '$5,000', '$15,000'], ['Plan 6 miesięcy', '180 dni', '5%', '$15,999', 'Bez limitu']];
doc.fontSize(10).fillColor('#444').font('ArialBold');
let ry = t + 22;
r.forEach((row, i) => {const cy = ry + (i * 18);if (i % 2 === 1) {doc.rect(15, cy, 565, 18).fillColor('#f9f9f9').fill();}doc.fillColor('#444');doc.text(row[0], 20, cy + 4, { width: 90 });doc.text(row[1], 110, cy + 4, { width: 110 });doc.text(row[2], 220, cy + 4, { width: 100 });doc.text(row[3], 330, cy + 4, { width: 85 });doc.text(row[4], 430, cy + 4, { width: 85 });});
doc.addPage();
doc.fontSize(12).fillColor('#FF8C37').font('ArialBold').text('Przykład Obliczenia');doc.moveDown(0.15);
doc.fontSize(10.5).fillColor('#444').font('ArialBold').text('Jeśli zainwestujesz 100 $ w plan 3-dniowy z 8% dziennie, po 3 dniach zarobisz 24 $. Możesz wybrać wycofanie kapitału i zysków lub reinwestowanie.', { width: 490, lineGap: 1.5 });doc.moveDown(0.25);
doc.fontSize(13).fillColor('#FF8C37').font('ArialBold').text('Jak to Działa');doc.moveDown(0.2);
doc.fontSize(10.5).fillColor('#444').font('ArialBold').text('Gdy inwestujesz w Grant Union, nasz profesjonalny zespół traderów handluje Twoją walutą Bitcoin przez czas trwania wybranego planu. Po okresie inwestycji Twój kapitał i zyski trafiają na Twoje zaplecze biurowe, gdzie możesz wybrać wycofanie lub reinwestowanie.', { width: 490, lineGap: 1.5 });
doc.moveDown(0.3);
doc.fontSize(13).fillColor('#FF8C37').font('ArialBold').text('Metody Płatności');doc.moveDown(0.2);
doc.fontSize(10.5).fillColor('#444').font('ArialBold').text('Grant Union używa Bitcoina i USDT do wszystkich transakcji na platformie, zapewniając szybki, bezpieczny i globalny dostęp.', { width: 490, lineGap: 1.5 });
doc.moveDown(1);
doc.addPage();
doc.fontSize(18).fillColor('#FF8C37').font('ArialBold').text('Prowizja Referralna');doc.moveTo(15, doc.y + 2).lineTo(580, doc.y + 2).strokeColor('#FF8C37').lineWidth(2.5).stroke();doc.moveDown(0.35);
doc.fontSize(13).fillColor('#FF8C37').font('ArialBold').text('Zarabiaj Nieograniczone Prowizje 10%');doc.moveDown(0.2);
doc.fontSize(10.5).fillColor('#444').font('ArialBold').text('Grant Union oferuje nieograniczone prowizje referencyjne w wysokości 10% dla wszystkich inwestorów! Zarabiaj 10% z każdego depozytu dokonanego przez każdą osobę, która rejestruje się za pomocą Twojego unikalnego linku referencyjnego.', { width: 490, lineGap: 1.5 });
doc.fontSize(10).fillColor('#444').font('ArialBold').text('© 2026 Grant Union. Wszystkie prawa zastrzeżone.', { align: 'center' });
doc.end();
doc.on('finish', () => {const s = fs.statSync(out);console.log(`✓ guide-pl.pdf: ${(s.size / 1024).toFixed(2)} KB`);});
