const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');
const doc = new PDFDocument({ size: 'A4', margin: 15, bufferPages: true });
const out = path.join(__dirname, 'public', 'downloads', 'guide-sv.pdf');
const logo = path.join(__dirname, 'public', 'grantunionLogo.png');
doc.pipe(fs.createWriteStream(out));
if (fs.existsSync(logo)) {
  const w = doc.page.width;
  doc.image(logo, (w - 75) / 2, 15, { width: 75, height: 50 });
  doc.moveDown(3);
}
doc.fontSize(26).fillColor('#FF8C37').font('Helvetica-Bold').text('GRANT UNION', { align: 'center' });
doc.moveDown(0.6);
doc.fontSize(18).fillColor('#FF8C37').font('Helvetica-Bold').text('Welcome to Grant Union');
doc.moveTo(15, doc.y + 2).lineTo(580, doc.y + 2).strokeColor('#FF8C37').lineWidth(2.5).stroke();
doc.moveDown(0.35);
doc.fontSize(10.5).fillColor('#444').font('Helvetica-Bold').text('Grant Union is the world\'s leading investment and trading platform.', { width: 490, lineGap: 1.5 });
doc.moveDown(0.5);
doc.fontSize(13).fillColor('#FF8C37').font('Helvetica-Bold').text('About Grant Union');
doc.moveDown(0.2);
doc.fontSize(10.5).fillColor('#444').font('Helvetica-Bold').text('Professional trading company for cryptocurrency, forex, gold, and real estate.', { width: 490, lineGap: 1.5 });
doc.moveDown(0.25);
doc.fontSize(12).fillColor('#FF8C37').font('Helvetica-Bold').text('Minimum Investment: $100');
doc.moveDown(0.2);
doc.fontSize(10.5).fillColor('#444').font('Helvetica-Bold').text('Start earning with flexible plans and daily commissions.', { width: 490, lineGap: 1.5 });
doc.moveDown(1);
doc.fontSize(18).fillColor('#FF8C37').font('Helvetica-Bold').text('Investment Plans');
doc.moveTo(15, doc.y + 2).lineTo(580, doc.y + 2).strokeColor('#FF8C37').lineWidth(2.5).stroke();
doc.moveDown(0.3);
const t = doc.y;
doc.fontSize(11).font('Helvetica-Bold').fillColor('#ffffff');
doc.rect(15, t, 565, 22).fillColor('#FF8C37').fill();
doc.text('Plan', 20, t + 6, { width: 90 });
doc.text('Duration', 110, t + 6, { width: 110 });
doc.text('Daily Comm.', 220, t + 6, { width: 120 });
doc.text('Min. Inv.', 350, t + 6, { width: 80 });
const plans = [['3-Day', '3 days', '8%', '$100'], ['7-Day', '7 days', '3%', '$100'], ['12-Day', '12 days', '3.5%', '$100'], ['15-Day', '15 days', '4%', '$100'], ['3-Month', '90 days', '4%', '$100'], ['6-Month', '180 days', '5%', '$100']];
doc.fontSize(10).fillColor('#444').font('Helvetica-Bold');
let ry = t + 22;
plans.forEach((row, i) => {
  const cy = ry + (i * 18);
  if (i % 2 === 1) doc.rect(15, cy, 565, 18).fillColor('#f9f9f9').fill();
  doc.fillColor('#444');
  doc.text(row[0], 20, cy + 4, { width: 90 });
  doc.text(row[1], 110, cy + 4, { width: 110 });
  doc.text(row[2], 220, cy + 4, { width: 120 });
  doc.text(row[3], 350, cy + 4, { width: 80 });
});
doc.addPage();
doc.fontSize(12).fillColor('#FF8C37').font('Helvetica-Bold').text('Referral Commission - 10%');
doc.moveDown(0.15);
doc.fontSize(10.5).fillColor('#444').font('Helvetica-Bold').text('Earn unlimited commission on all referrals.', { width: 490, lineGap: 1.5 });
doc.moveDown(0.25);
doc.fontSize(13).fillColor('#FF8C37').font('Helvetica-Bold').text('Withdrawal');
doc.moveDown(0.2);
doc.fontSize(10.5).fillColor('#444').font('Helvetica-Bold').text('Fast withdrawals within 24 hours.', { width: 490, lineGap: 1.5 });
doc.moveDown(0.25);
doc.fontSize(13).fillColor('#FF8C37').font('Helvetica-Bold').text('Security');
doc.moveDown(0.2);
doc.fontSize(10.5).fillColor('#444').font('Helvetica-Bold').text('Advanced security measures protect your funds and personal information.', { width: 490, lineGap: 1.5 });
doc.moveDown(1);
doc.fontSize(10).fillColor('#444').font('Helvetica-Bold').text('© 2026 Grant Union. All rights reserved.', { align: 'center' });
doc.fontSize(9).text('Email: grantunion583@gmail.com | Website: grantunion.vercel.app', { align: 'center' });
doc.end();
doc.on('finish', () => { console.log('✓ guide-sv.pdf'); });
